### PR TITLE
Feature 20181030

### PR DESCRIPTION
**Pull request by markreds81**
Added a new item in date range popup menu called "Last twelve months" to show last twelve months before current date.

### CODE REVIEW

**Comment by hsoft** [comment]
How is that different from "Running year"?

Also: There's not much of a point in integrating code in moneyguru-cocoa in the form of a PR: I don't have a mac, I can't even try it. The idea is more that you entirely take care of anything mac-related, without me getting involved anymore. I would then add a link to your mac builds in moneyGuru's home page.

**Comment by markreds81** [comment]
"Running year" shows me current solar year: for example now it shows me 01 Jan - 31 Dec (2018) while my feature shows 31 Oct 2017 - 31 Oct 2018.

How can I take care of the entire process? Should I make changes to a new repository instead of a pull requests on a forked one? Otherwise how can I can add new features or fixes to codes without write access?

**Comment by hsoft** [comment]
https://www.hardcoded.net/moneyguru/help/en/basics.html#the-date-range

Running year is "current month + ahead months, 1 year span". one could set his ahead months to 0 to get the same range.

**Comment by hsoft** [comment]
You already have a forked repo. Use this, then make a MacOS build and put it somewhere. When it's done, tell me, I'll add a "Mac builds are available at <link>" to moneyguru's home page.

If you mean changes to moneyguru's repo (not moneyguru-cocoa), if you need something in that repo to make the mac build work properly, then you can open a PR, I'll review it.

**Comment by markreds81** [comment]
Yes, but how can I set months to 0? I didn't found any preferences about that and when I select "Running year" as range moneyGuru shows me the entire solar year.

**Comment by hsoft** [comment]
New tab -> Document Properties -> Ahead months in Running year

**Comment by markreds81** [comment]
Oh sorry, I never tried to click on new tab before now and I didn't know about commands on this pane. Maybe it could be useful make them more accessible?
Anyway at this point this feature became unuseful.

**Pull request closed without merging**
